name: unit tests CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean compile package
      - name: Report
          uses: dorny/test-reporter@v1
          if: success() || failure()
          with:
            name: Maven Tests
            path: target/surefire-reports/*.xml
            reporter: java-junit
            fail-on-error: true